// Generated by https://quicktype.io

export interface AuthResponse {
    ok?:    boolean;
    msg?:   string;
    uid?:   number;
    name?:  string;
    token?: string;
}

export interface User {
    uid: number,
    name: string,
}